package com.tieto.frameworkServices.core;

public enum WaitType {

	    WAITFORELEMENTTOBEEENABLED, 
	    WAITFORELEMENTTOBEDISPLAYED, 
	    WAITFORELEMENTTOBECLICKABLE, 
	    WAITFORELEMENTTODISAPPEAR
	}

